### PR TITLE
ICOFamily is no longer broken - writing ICO files works.

### PR DESCRIPTION
**Pull request by matheweis**
Functional in simple tests, but needs more testing for edge cases; it
makes heavy assumptions about the internal format of the
NSBitmapImageReps and has no error checking. At least it works now.

### CODE REVIEW

**Comment by alexzielenski** [comment]
Wow, thanks I just merged it. I would have worked on this class more but the project I was using it in is no longer in development.

**Comment by alexzielenski** [comment]
Can you tell me the function of the andBuf?

**Comment by matheweis** [comment]
Hi Alex,

Sure, it is basically a 1-bit mask... It makes more sense if you think about the 1-bit and 8-bit icons.

It is confusing that it is still required for 32-bit formats since they have their own 8-bit alpha as well... I have tried making 32-bit ico bitmaps without the and mask but many applications have trouble parsing them.

By the way, what were you planning to make out of ICOFamily?

Please let me know if you need any more info.

Thanks,

-Mathew Eis

**Comment by matheweis** [comment]
I should add that I took advantage of that fact and hacked the andBuf... really the data should be generated based on the 8-bit alpha channel, but since most apps will ignore the andBuf it didn't matter.

I just wanted to get it working to see if ICOFamily would work for my application and thought I might as well contribute that source back up.

-Mathew Eis

**Comment by alexzielenski** [comment]
Ok that makes sense. Also, why does the and mask require double height? And I was planning on making ICOFamily an ICO counterpart to IconFamily.

**Comment by matheweis** [comment]
The double height seems to be a (painfully undocumented) way to indicate that the image data contains two images; the actual data, then the mask... I can't really be sure. It is not mentioned on MSDN at all, but every ICO reader/writer I have seen uses it, and if it is left out some apps have trouble reading the data.

I found that for my app I need an ICO writer that uses CGImageRef natively, so I am writing my own from scratch.  IconFamily uses NSBitmapImageRep which stores data in premultiplied alpha format - convenient for use with NSImage, but data is lost over time.

If you need some more guidance on reading/writing ICO directly, you should look at these three programs:
http://www.macupdate.com/download/9477/Iconverterv09.zip
http://savannah.nongnu.org/download/icoutils/icoutils-0.29.1.tar.bz2
http://www.ibiblio.org/pub/linux/libs/graphics/libico-1.2.tar.gz

Hope this helps,

-Mathew Eis

**Comment by alexzielenski** [comment]
NSBitmapImageRep has a -CGImage method

**Comment by matheweis** [comment]
NSBitmapImageRep does not support unpremultiplied alpha format, so data will be lost when converting from CGImageRef (unpremultiplied alpha) to NSBitmapImageRep (premultiplied alpha)

**Pull request merged**
